name: postgres

services:
  db:
    image: postgres:17.0-alpine
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  gui:
    image: dpage/pgadmin4:8.12
    restart: always
    env_file:
      - ./env/gui.env
    ports:
      - 8000:80
    volumes:
      - gui-data:/var/lib/pgadmin

volumes:
  db-data:
  gui-data:
